name: Publish to npm

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/sdk/js
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm install

      - name: Publish JS SDK to NPM
        run: npm publish --workspace=sdk/js
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish React components to NPM
        run: npm publish --workspace=ui/lib
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
